config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :comments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_rich_text :content
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  
  has_one_attached :cover
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def index
    @post = Post.find(params[:post_id])
    
  end
  
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@comment.post_id) }
        format.turbo_stream 
      else
        format.html { redirect_to post_path(@comment.post_id), notice: "No pudimos añadir el comentario" }
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :post_id, :title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "landing"
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  layout :set_layout

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new(post_id: @post.id)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :cover, :content)
    end

    def set_layout
      # %w(show).include?(action_name) ? "landing" : "application"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/application/_footer.html.erb
<footer class="bg-dark p-4 text-white">
  <p class="m-0">MiBlog &copy; <%= Time.now.year %></p>
</footer>

app/views/application/_toast.html.erb
<div class="toast-container position-fixed bottom-0 end-0 p-3">
  <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
      <%# <img src="..." class="rounded me-2" alt="..."> %>
      <strong class="me-auto">Cody</strong>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
      <%= message %>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="mt-2 border-bottom py-4">
  <p class="h5"><%= comment.title %></p>
  <p class="fs-6 text-secondary">
    <strong>Por: </strong>
    <%= comment.user.email %>
  </p>
  <div class="mt-1"><%= comment.content %></div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: @comment ) do |f| %>
  <%= f.hidden_field :post_id %>
  <div class="field">
    <%= f.label :title, class:"form-label" %>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :content, class:"form-label" %>
    <%= f.rich_text_area :content, class:"form-control" %>
  </div>
  <div class="field my-2">
    <%= f.button class:"btn btn-primary" do %>
      <i class="bi bi-send-fill"></i>
      Publicar
    <%end%>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend(:comments, partial: "comments/comment",locals: { comment: @comment }) %>

app/views/comments/index.html.erb
<%= turbo_frame_tag "comments" do %>
  <%= render @post.comments %>
<%end%>

app/views/home/index.html.erb
<header class="cover p-4 mb-4">
  <h1>Mi blog personal</h1>
  <p>Uriel Hernández, Web Developer</p>
</header>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "toast", message: "Hola mundo" %>
    <section class="layout">
      <header class="main-nav p-4">
        <nav class="nav">
          <%=link_to root_path, class:"nav-link" do%>
            <%=image_tag "logo.png", height:20 %>
          <%end%>
          <%=link_to "Inicio", root_path, class:"nav-link"%></li>
          <%=link_to "Artículos", posts_path, class:"nav-link" %>
          <%= button_tag "Salúdame",id: "toast-trigger" %>
          <%= link_to "Nuevo post", new_post_path, class:"nav-link" %>
        </nav>
      </header>
      <main class=""><%= yield %></main>
      <%= render "footer" %>
    </section>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "landing", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class=""><%= yield %></main>
  </body>
</html>

app/views/posts/_card.html.erb
<article class="post <%=('no-cover' unless post.cover.attached?)%>">
  <% if post.cover.attached? %>
    <div class="post--cover" style="background-image:url(<%= url_for(post.cover) %>)"></div>
  <%end%>
  <div class="post--body p-3">
    <p class="h2 m-0"><%= post.title %></p>
    <p class="text-secondary fs-6">
      <%= time_ago_in_words post.created_at %> ago
    </p>
    <p>
      <strong>Por: </strong>
      <%= post.user.email %>
    </p>
    <%# <p>
      <%= truncate post.title, lenght: 100 
    </p> %>
    
  </div>
  <div class="mt-2 p-3">
    <%= link_to "Leer más",post, class:"btn btn-outline-dark d-block"%>
  </div>
</article>
  

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :cover, style: "display: block" %>
    <%= form.file_field :cover %>
  </div>

  <%# <div>
    <%= form.label :body, style: "display: block" 
    <%= form.text_area :body 
  </div> %>

  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<header class="cover p-4 mb-4">
  <h1>Mi blog personal</h1>
  <p>Uriel Hernández, Web Developer</p>
</header>

<section class="p-4">
  <header>
    <h2> Últimas publiaciones </h2>
    
  </header>
  <div id="posts" class="d-flex gap-3 sjustify-content-center">
    <%#= render partial: "posts/post", collection: @posts %>
    <%= render partial: "posts/card", collection: @posts, as: :post %>
  </div>
</section>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-sm app-container">
  <% if @post.cover.attached? %>
    <div class="post--cover" style="background-image:url(<%= url_for(@post.cover) %>)"></div>
  <%end%>
  <h1 class="mt-2 fw-bold"><%= @post.title %></h1>
  <%= link_to "Regresar", posts_path %>
  <div class="mt-4 border-bottom pb-3"><%= @post.content %></div>

  <div class="mt-4">
    <p class="h3">Qué opinas del tema</p>
    <%= render "comments/form" %>
    <%# <%= turbo_frame_tag "comments", class:'my-3', src:"/comments?post_id=#{@post.id}" do 
      <p>Cargando comentarios...</p>
    <%end%> 

    <%= turbo_frame_tag "comments", class:'my-3  d-block' do %>
      <div class="text-center"><%= link_to "Cargar comentarios (#{@post.comments.count})", comments_path(post_id: @post.id) %></div>
    <%end%>
    
  </div>
  
</div>

<% if current_user == @post.user  %>
  <div>
    <%= link_to "Edit this post", edit_post_path(@post) %> |
    

    <%= button_to "Destroy this post", @post, method: :delete %>
  </div>
<% end %>